font_family      family='ComicShannsMono Nerd Font Mono'
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11
line_height      2
adjust_line_height 1
adjust_column_width 1
disable_ligatures never
font_hinting slight
window_margin_width 15
window_padding_width 13
confirm_os_window_close 0
resize_in_steps no
window_resize_step_cells 2
window_resize_step_lines 2
cursor_shape beam
cursor_blink_interval 0.6
cursor_stop_blinking_after 15.0
cursor_foreground #89b4fa
scrollback_lines 100000
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0
background_opacity 0.95
background_blur 0
dim_inactive_windows yes
inactive_text_alpha 0.9
foreground #d0c0f5  
background #1a1b26
selection_background #3d2f55 
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
tab_title_template "{cwd##*/}"
active_tab_foreground #9a7ff7 
active_tab_background #bfa3ff  
inactive_tab_background #2c2b3c 
tab_bar_margin_height 0 6
tab_bar_min_tabs 2
inactive_tab_foreground #7dcfff
shell_integration enable
window_title_format "{cwd##*/} — {cmdline}"
enable_audio_bell no
visual_bell_duration 0.0
detect_urls yes
open_url_with default
copy_on_select yes
strip_trailing_spaces smart
repaint_delay 10
input_delay 3
sync_to_monitor yes
map ctrl+shift+r load_config_file
map ctrl+shift+w close_window
map ctrl+shift+enter new_window
map ctrl+shift+t new_tab
map ctrl+shift+o open_url
selection_foreground none
color0  #1a1b26 
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #b39df7
color5  #bb9af7
color6  #8f7fff
color7  #937fd4  
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68 
color12 #b39df7
color13 #9c7bd9
color14 #8f7fff
color15 #ffffff 
url_color #7dcfff
underline_hyperlinks always
enable_wayland_clipboard yes
